{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "remote.serviceAccountName" . }}
  labels:
{{ include "remote.labels" . | nindent 4 }}
{{- end -}}
